import { jsonOk, jsonError } from "./http.js";

export const BOARD_STAMPS = Object.freeze(["☕","✦","🌙","🍰","💗","🎧","🎀","🍾"]);
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const enc=new TextEncoder(), dec=new TextDecoder();
const b64=a=>btoa(String.fromCharCode(...a)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const unb64=s=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((s.length+3)%4)),c=>c.charCodeAt(0));
export const encodeBoardCursor=p=>b64(enc.encode(JSON.stringify([p.created_at,p.id])));
export function decodeBoardCursor(s){if(!s)return null;try{const v=JSON.parse(dec.decode(unb64(s)));return Array.isArray(v)&&v.length===2&&Number.isSafeInteger(v[0])&&v[0]>=0&&UUID_RE.test(v[1])?{createdAt:v[0],id:v[1]}:false}catch{return false}}
const ready=e=>e?.BOARD_DB&&typeof e.BOARD_DB.prepare==="function";
const origin=(r,v)=>r.headers.get("origin")===v;
async function digest(v){return b64(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(v))))}
async function identity(r,e,n){const k=await crypto.subtle.importKey("raw",enc.encode(String(e.BOARD_RATE_LIMIT_SECRET||"")),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const d=new Date(n).toISOString().slice(0,10),ip=r.headers.get("CF-Connecting-IP")||"unknown";return b64(new Uint8Array(await crypto.subtle.sign("HMAC",k,enc.encode(`${d}\n${ip}`))))}
function normalize(v){if(!v||Object.getPrototypeOf(v)!==Object.prototype)return null;const keys=["name","body","stamp","turnstileToken"];if(Object.keys(v).length!==4||Object.keys(v).some(k=>!keys.includes(k))||keys.some(k=>typeof v[k]!=="string"))return null;const name=v.name.normalize("NFC").trim(),body=v.body.normalize("NFC").trim(),nameLength=Array.from(name).length,bodyLength=Array.from(body).length;if(nameLength>16||bodyLength<1||bodyLength>140||!BOARD_STAMPS.includes(v.stamp)||!v.turnstileToken)return null;return{name:name||"ななしさん",body,stamp:v.stamp,turnstileToken:v.turnstileToken}}
async function input(r){if((r.headers.get("content-type")||"").split(";",1)[0].trim().toLowerCase()!=="application/json")return{error:"BAD_JSON_TYPE"};if(Number(r.headers.get("content-length")||0)>4096)return{error:"TOO_LARGE"};const a=await r.arrayBuffer();if(a.byteLength>4096)return{error:"TOO_LARGE"};try{return{value:JSON.parse(dec.decode(a))}}catch{return{error:"BAD_REQUEST"}}}
async function turnstile(token,r,e,f){if(!e.TURNSTILE_SECRET_KEY)return false;try{const x=new FormData();x.set("secret",e.TURNSTILE_SECRET_KEY);x.set("response",token);const ip=r.headers.get("CF-Connecting-IP");if(ip)x.set("remoteip",ip);const q=await f("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body:x});return q.ok&&(await q.json())?.success===true}catch{return false}}

export async function handleBoardList(r,e){if(r.method!=="GET")return jsonError("NOT_FOUND");if(!ready(e))return jsonError("BOARD_UNAVAILABLE");const u=new URL(r.url);if([...u.searchParams.keys()].some(k=>k!=="limit"&&k!=="cursor"))return jsonError("BAD_REQUEST");const raw=u.searchParams.get("limit"),limit=raw===null?30:Number(raw),cursor=decodeBoardCursor(u.searchParams.get("cursor"));if(!Number.isInteger(limit)||limit<1||limit>50||cursor===false)return jsonError("BAD_REQUEST");try{let sql="SELECT id,name,body,stamp,created_at FROM board_posts WHERE status='active'",args=[];if(cursor){sql+=" AND (created_at<? OR (created_at=? AND id<?))";args.push(cursor.createdAt,cursor.createdAt,cursor.id)}sql+=" ORDER BY created_at DESC,id DESC LIMIT ?";args.push(limit+1);const out=await e.BOARD_DB.prepare(sql).bind(...args).all(),rows=Array.isArray(out.results)?out.results:[],posts=rows.slice(0,limit);return jsonOk({ok:true,posts,nextCursor:rows.length>limit?encodeBoardCursor(posts.at(-1)):null})}catch{return jsonError("BOARD_UNAVAILABLE")}}

export async function handleBoardPost(r,e,deps={}){if(r.method!=="POST")return jsonError("NOT_FOUND");if(!ready(e)||!e.BOARD_RATE_LIMIT_SECRET||!e.TURNSTILE_SECRET_KEY)return jsonError("BOARD_UNAVAILABLE");const expectedOrigin=String(e.ENVIRONMENT||"")==="local"?"http://127.0.0.1:8787":`https://${String(e.PUBLIC_HOST||"")}`;if(!origin(r,expectedOrigin))return jsonError("FORBIDDEN");const parsed=await input(r);if(parsed.error)return jsonError(parsed.error);const v=normalize(parsed.value);if(!v)return jsonError("BAD_REQUEST");if(!await turnstile(v.turnstileToken,r,e,deps.fetch||fetch))return jsonError("TURNSTILE_FAILED");const now=(deps.now||Date.now)(),id=(deps.randomUUID||crypto.randomUUID)(),who=await identity(r,e,now),hash=await digest(v.body);try{await e.BOARD_DB.prepare("DELETE FROM board_rate_limits WHERE expires_at<=?").bind(now).run();await e.BOARD_DB.prepare("DELETE FROM board_recent_content WHERE expires_at<=?").bind(now).run()}catch{}try{const rate=await e.BOARD_DB.prepare(`INSERT INTO board_rate_limits(identity_hash,last_post_at,window_start,window_count,expires_at) VALUES(?,?,?,1,?) ON CONFLICT(identity_hash) DO UPDATE SET last_post_at=excluded.last_post_at,window_start=CASE WHEN excluded.last_post_at-board_rate_limits.window_start>=600000 THEN excluded.last_post_at ELSE board_rate_limits.window_start END,window_count=CASE WHEN excluded.last_post_at-board_rate_limits.window_start>=600000 THEN 1 ELSE board_rate_limits.window_count+1 END,expires_at=excluded.expires_at WHERE excluded.last_post_at-board_rate_limits.last_post_at>=30000 AND (excluded.last_post_at-board_rate_limits.window_start>=600000 OR board_rate_limits.window_count<5) RETURNING identity_hash`).bind(who,now,now,now+172800000).first();if(!rate)return jsonError("RATE_LIMITED");const unique=await e.BOARD_DB.prepare(`INSERT INTO board_recent_content(identity_hash,body_hash,created_at,expires_at) VALUES(?,?,?,?) ON CONFLICT(identity_hash,body_hash) DO UPDATE SET created_at=excluded.created_at,expires_at=excluded.expires_at WHERE board_recent_content.expires_at<=excluded.created_at RETURNING body_hash`).bind(who,hash,now,now+600000).first();if(!unique)return jsonError("DUPLICATE_POST");const post=await e.BOARD_DB.prepare(`INSERT INTO board_posts(id,name,body,stamp,created_at,status) SELECT ?,?,?,?,?,'active' WHERE (SELECT active_count FROM board_state WHERE singleton=1)<5000 RETURNING id,name,body,stamp,created_at`).bind(id,v.name,v.body,v.stamp,now).first();return post?jsonOk({ok:true,post},201):jsonError("BOARD_FULL")}catch{return jsonError("BOARD_UNAVAILABLE")}}

export async function handleBoardDelete(r,e,id){if(r.method!=="DELETE")return jsonError("NOT_FOUND");if(!ready(e))return jsonError("BOARD_UNAVAILABLE");if(!origin(r,`https://${String(e.ADMIN_HOST||"")}`))return jsonError("FORBIDDEN");if(!UUID_RE.test(id))return jsonError("BAD_REQUEST");try{const row=await e.BOARD_DB.prepare("UPDATE board_posts SET status='deleted',deleted_at=? WHERE id=? AND status='active' RETURNING id").bind(Date.now(),id).first();return row?jsonOk({ok:true,id}):jsonError("NOT_FOUND")}catch{return jsonError("BOARD_UNAVAILABLE")}}
